### ISSUE TITLE
Teacher app needs to handle "retake" scenario

### ISSUE THREAD

**Issue by chrqls** [RazortoothRTC/smile_teacher_android#23] opened 2014-02-15 11:57 UTC
Relative issue: https://github.com/SMILEConsortium/smile_teacher_android/issues/7

**Comment by chrqls** [comment] 2014-02-15 11:58
![screen shot 2014-02-15 at 03 57 33](https://f.cloud.github.com/assets/3521208/2177771/6c7e802c-9638-11e3-800f-840db1ae9990.png)

**Comment by chrqls** [comment] 2014-02-15 11:58
![screen shot 2014-02-15 at 03 58 57](https://f.cloud.github.com/assets/3521208/2177775/a734e54e-9638-11e3-8e4e-8549c712c3b2.png)

**Comment by truedat101** [comment] 2014-02-19 04:17
@chrqls  can you look into this feature?  It's partially implemented.  JAMsj would like this feature done in this manner:
- Teacher selects retake from menu.
- Server resets scores, drops all current questions, but leaves the students logged into the session
- Student devices are sent back to "start making questions" phase.  They aren't logged out.

**Comment by truedat101** [comment] 2014-02-19 04:17
The use case for JAMsj is to easily send out a new batch of questions without forcing all students to re-login.

**Comment by chrqls** [comment] 2014-03-03 19:25
I identified a problem with the json request caught on server side, but I did not find a solution for now

#### format I need

``` json
{"MSG":"{\"TYPE\":\"HAIL\",\"IP\":\"127.0.0.239\",\"NAME\":\"mac\"}"}
```

#### format we have

``` json
{"MSG\":\"{\"RANSWER\":[4,4,4,4],\"TIME_LIMIT\":10,\"NUMQ\":4}\"}":""}
```

For a reason I cannot explain for now, the json is not wrapped correctly when I call . 
I try to change that.

**Comment by truedat101** [comment] 2014-03-04 17:06
There's probably bugs in the "retake" because this was never completely implemented.  The code partially exists on both sides.  As you can see @thiago didn't completely finish this feature.  I would like it if you can focus on this, how to implement per the JAMsj requirement:
- Teacher runs a session with prepared question set A
- Teacher completes session, would like to run prepared question Set B.
- Teacher hits "Send New IQSet" button
- This should restart the teacher tablet, with the selection of prepared questions
- Once selected an iqset, students are reset to "Start Answer Questions Phase" without being logged out, and all existing scores are reset. 

Note, this requires a server side change as well.

**Comment by truedat101** [comment] 2014-04-09 05:24
Feature is not fixed or not working as intended.  When the teacher performs retake, everything goes fine in the teacher interface.  However, in the SMILE Student Web app, they  don't receive questions.  The question count is 1/0 ... 

Did you verify this before closing?  Please provide a screenshot for verification purposes, and let me handle closing of the issue as verification.

**Comment by truedat101** [comment] 2014-04-09 05:28
After "retake"

![screenshot_2014-04-08-22-19-48](https://cloud.githubusercontent.com/assets/64202/2652279/98460b06-bfa7-11e3-8458-1aab2eec3cff.png)

After teacher hits "Start Answer Questions"

![screenshot_2014-04-08-22-23-44](https://cloud.githubusercontent.com/assets/64202/2652281/a5f2d66c-bfa7-11e3-84f4-8b594fdbc080.png)

**Comment by truedat101** [comment] 2014-04-09 05:28
Note, there are no questions.  Dataset used is from an uploaded XLS spreadsheet.

**Comment by chrqls** [comment] 2014-04-11 15:07
This problem won't appear anymore now.  The students won't get empty questions with this new fix on node-smile-server. Henceforth, the teacher is also able to delete questions from a retaken iqset.

**Comment by truedat101** [comment] 2014-04-12 10:31
verified.

**Closed as completed by truedat101** 2014-04-12 10:31 UTC
